package UppercaseModule;


/**
* UppercaseModule/Uppercase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Uppercase.idl
* Thursday, 7 May, 2026 2:53:18 AM IST
*/

public interface Uppercase extends UppercaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Uppercase
