package UppercaseModule;


/**
* UppercaseModule/UppercaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Uppercase.idl
* Thursday, 7 May, 2026 2:53:18 AM IST
*/

public interface UppercaseOperations 
{
  String uppercase_string (String str);
} // interface UppercaseOperations
